### ISSUE TITLE
Tutorial Task - Zach

### ISSUE THREAD

**Issue by kennybytes** [scel-hawaii/git-playground#2]
Add your name to the readme file.

**Comment by kennybytes** [comment]
@Irreverence where's that commit D:<

**Comment by Irreverence** [comment]
sorry git was linked to this email account so I forgot about it (most of my
emails are forwarded from my edu email so I skim through it and delete it
on this email, knowing that I will see it again on my edu email)

**Comment by kennybytes** [comment]
![jordan-fist-bump](https://cloud.githubusercontent.com/assets/1109418/5990125/b87fd7a6-a946-11e4-87fa-4aaa4581786b.gif)

all done - close the issue now!

**Comment by kennybytes** [comment]
Wait a minute - I rescend my previous fist bump - where's that merge request? From https://github.com/scel-hawaii/software-team-minutes/blob/master/2015-01-29.markdown

Steps:

```
Comment on the issue that was assigned to you, noting that you saw it
Clone git-playground repository
Go to the command line and create your own branch. Name it Feature/Task1YourFullName
Add your name under the authors section
Commit
Push
Submit a merge request to the master repository
Tag me in the merge request
I'll double check your request and merge it
Comment on your original issue and close it!
```

**Comment by Irreverence** [comment]
didn't think I needed to make my own branch to add a name...

Wait a minute - I recent my previous fist bump - where's that merge request?

Steps:

Comment on the issue that was assigned to you, noting that you saw it
Clone git-playground repository
Go to the command line and create your own branch. Name it
Feature/Task1YourFullName
Add your name under the authors section
Commit
Push
Submit a merge request to the master repository
Tag me in the merge request
I'll double check your request and merge it
Comment on your original issue and close it!

**Comment by kennybytes** [comment]
Just as an exercise. Eventually, I'd like the modules for the weatherbox to be handled that way.

**Comment by Irreverence** [comment]
yeah I understand lol

**Comment by kennybytes** [comment]
@Irreverence: can you repeat the procedure with the pull request?

**Comment by kennybytes** [comment]
@Irreverence see https://help.github.com/articles/using-pull-requests/

**Comment by kennybytes** [comment]
also the discussion on issue #3 with ryan
