### ISSUE TITLE
Tutorial Task - Ryan

### ISSUE THREAD

**Issue by kennybytes** [scel-hawaii/git-playground#3]
Add your name to the readme file. 

Refer to the minutes for instructions: https://github.com/scel-hawaii/software-team-minutes/blob/master/2015-01-29.markdown

**Comment by MasaharuKage** [comment]
Seen

**Comment by kennybytes** [comment]
@MasaharuKage: let's repeat this procedure with the pull request instead. Be sure to push your branch up. You can see this page for more information on pull requests: https://help.github.com/articles/using-pull-requests/

We're using the shared repository model:

> The shared repository model is more prevalent with small teams and organizations collaborating on private projects. Everyone is granted push access to a single shared repository and topic branches are used to isolate changes.
> 
> Pull requests are especially useful in the fork & pull model because they provide a way to notify project maintainers about changes in your fork. However, they're also useful in the shared repository model where they're used to initiate code review and general discussion about a set of changes before being merged into a mainline branch.

**Comment by MasaharuKage** [comment]
Merge Successful
