### ISSUE TITLE
Tutorial Task - Michele

### ISSUE THREAD

**Issue by kennybytes** [scel-hawaii/git-playground#4]
Add your name to the readme. Here's your motivating cat picture to help get the job done:

![cat](https://cloud.githubusercontent.com/assets/1109418/5987290/983316c8-a8c6-11e4-9ae5-3dd413cc0102.jpg)

Refer to the minutes for some instructions: https://github.com/scel-hawaii/software-team-minutes/blob/master/2015-01-29.markdown

**Comment by kennybytes** [comment]
Quick reminder to get this done before the Thursday (2/5/15) all-hands meeting at 12:30pm.

**Comment by mkshimoda** [comment]
Seen.

**Comment by kennybytes** [comment]
Please close when you're done.
